FROM apache/airflow:2.10.0-python3.11

USER root
RUN apt-get update && apt-get install -y default-jdk procps && apt-get clean
ENV JAVA_HOME=/usr/lib/jvm/default-java
USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt